#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += KD080D24_40NH_B3_MIPI.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/include
