#include $(srctree)/drivers/misc/mediatek/Makefile.custom

#obj-y := stk8312_cust_acc.o
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y   +=  stk831x.o
