#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += KD089D7_40NI_A6_MIPI.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/include
