#
# Makefile for misc devices that really don't fit anywhere else.
#


obj-y += KD080D34_40NI_C6_DSI_MIPI.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/include
