include $(srctree)/drivers/misc/mediatek/Makefile.custom
include $(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/imgsensor/src/Makefile.custom

obj-y += $(subst ",,$(CONFIG_MTK_PLATFORM_SENSOR))/

